    nginx:
        restart: always
        build: ./nginx
        expose:
            - "80"
        links:
            - php-fpm:php-fpm
        volumes_from:
            - php-fpm
        environment:
            - VIRTUAL_HOST=mmi.jakobi.club
            - VIRTUAL_PROTO=http
            - LETSENCRYPT_HOST=mmi.jakobi.club
    php-fpm:
        restart: always
        build: .
        links:
            - mysql:mysql
        volumes:
            - ./app:/app
    mysql:
        restart: always
        image: mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=wbh102019root
            - MYSQL_DATABASE=mmi
            - MYSQL_USER=mmi
            - MYSQL_PASSWORD=wbh102019user
